-- USERS 안에 있는 데이터는 INSERT 보다, 회원가입으로 등록해서 사용할 것(salt떄문). -> INSERT 는 한 줄씩 실행


-- ORDER_NUM INSERT

INSERT INTO ORDER_NUM (ORDER_NUM) VALUES (0);



-- STORE INSERT

INSERT INTO STORE (S_NAME, S_ADDRESS, S_PHONE, S_IMAGE, S_THUMB, S_OPENING, S_CLOSING, S_COMMENT, S_ANNOUNCE) VALUES ('S_NAME 01', 'S_ADDRESS 01', 'S_PHONE 01', 'S_IMAGE 01', 'S_THUMB 01', 'S_OPENING 01', 'S_CLOSING 01', 'S_COMMENT 01', 'S_ANNOUNCE 01');
INSERT INTO STORE (S_NAME, S_ADDRESS, S_PHONE, S_IMAGE, S_THUMB, S_OPENING, S_CLOSING, S_COMMENT, S_ANNOUNCE) VALUES ('S_NAME 02', 'S_ADDRESS 02', 'S_PHONE 02', 'S_IMAGE 02', 'S_THUMB 02', 'S_OPENING 02', 'S_CLOSING 02', 'S_COMMENT 02', 'S_ANNOUNCE 02');
INSERT INTO STORE (S_NAME, S_ADDRESS, S_PHONE, S_IMAGE, S_THUMB, S_OPENING, S_CLOSING, S_COMMENT, S_ANNOUNCE) VALUES ('S_NAME 03', 'S_ADDRESS 03', 'S_PHONE 03', 'S_IMAGE 03', 'S_THUMB 03', 'S_OPENING 03', 'S_CLOSING 03', 'S_COMMENT 03', 'S_ANNOUNCE 03');
INSERT INTO STORE (S_NAME, S_ADDRESS, S_PHONE, S_IMAGE, S_THUMB, S_OPENING, S_CLOSING, S_COMMENT, S_ANNOUNCE) VALUES ('S_NAME 04', 'S_ADDRESS 04', 'S_PHONE 04', 'S_IMAGE 04', 'S_THUMB 04', 'S_OPENING 04', 'S_CLOSING 04', 'S_COMMENT 04', 'S_ANNOUNCE 04');
INSERT INTO STORE (S_NAME, S_ADDRESS, S_PHONE, S_IMAGE, S_THUMB, S_OPENING, S_CLOSING, S_COMMENT, S_ANNOUNCE) VALUES ('S_NAME 05', 'S_ADDRESS 05', 'S_PHONE 05', 'S_IMAGE 05', 'S_THUMB 05', 'S_OPENING 05', 'S_CLOSING 05', 'S_COMMENT 05', 'S_ANNOUNCE 05');
INSERT INTO STORE (S_NAME, S_ADDRESS, S_PHONE, S_IMAGE, S_THUMB, S_OPENING, S_CLOSING, S_COMMENT, S_ANNOUNCE) VALUES ('S_NAME 06', 'S_ADDRESS 06', 'S_PHONE 06', 'S_IMAGE 06', 'S_THUMB 06', 'S_OPENING 06', 'S_CLOSING 06', 'S_COMMENT 06', 'S_ANNOUNCE 06');
INSERT INTO STORE (S_NAME, S_ADDRESS, S_PHONE, S_IMAGE, S_THUMB, S_OPENING, S_CLOSING, S_COMMENT, S_ANNOUNCE) VALUES ('S_NAME 07', 'S_ADDRESS 07', 'S_PHONE 07', 'S_IMAGE 07', 'S_THUMB 07', 'S_OPENING 07', 'S_CLOSING 07', 'S_COMMENT 07', 'S_ANNOUNCE 07');
INSERT INTO STORE (S_NAME, S_ADDRESS, S_PHONE, S_IMAGE, S_THUMB, S_OPENING, S_CLOSING, S_COMMENT, S_ANNOUNCE) VALUES ('S_NAME 08', 'S_ADDRESS 08', 'S_PHONE 08', 'S_IMAGE 08', 'S_THUMB 08', 'S_OPENING 08', 'S_CLOSING 08', 'S_COMMENT 08', 'S_ANNOUNCE 08');
INSERT INTO STORE (S_NAME, S_ADDRESS, S_PHONE, S_IMAGE, S_THUMB, S_OPENING, S_CLOSING, S_COMMENT, S_ANNOUNCE) VALUES ('S_NAME 09', 'S_ADDRESS 09', 'S_PHONE 09', 'S_IMAGE 09', 'S_THUMB 09', 'S_OPENING 09', 'S_CLOSING 09', 'S_COMMENT 09', 'S_ANNOUNCE 09');
INSERT INTO STORE (S_NAME, S_ADDRESS, S_PHONE, S_IMAGE, S_THUMB, S_OPENING, S_CLOSING, S_COMMENT, S_ANNOUNCE) VALUES ('S_NAME 10', 'S_ADDRESS 10', 'S_PHONE 10', 'S_IMAGE 10', 'S_THUMB 10', 'S_OPENING 10', 'S_CLOSING 10', 'S_COMMENT 10', 'S_ANNOUNCE 10');



-- PRODUCT INSERT, 필요하면 더 인서트 할 것.

INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (01, 'PRODUCT_NAME 01', 01, 'PRODUCT_INFO 01', 'PRODUCT_IMG 01');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (02, 'PRODUCT_NAME 02', 02, 'PRODUCT_INFO 02', 'PRODUCT_IMG 02');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (03, 'PRODUCT_NAME 03', 03, 'PRODUCT_INFO 03', 'PRODUCT_IMG 03');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (04, 'PRODUCT_NAME 04', 04, 'PRODUCT_INFO 04', 'PRODUCT_IMG 04');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (05, 'PRODUCT_NAME 05', 05, 'PRODUCT_INFO 05', 'PRODUCT_IMG 05');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (06, 'PRODUCT_NAME 06', 06, 'PRODUCT_INFO 06', 'PRODUCT_IMG 06');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (07, 'PRODUCT_NAME 07', 07, 'PRODUCT_INFO 07', 'PRODUCT_IMG 07');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (08, 'PRODUCT_NAME 08', 08, 'PRODUCT_INFO 08', 'PRODUCT_IMG 08');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (09, 'PRODUCT_NAME 09', 09, 'PRODUCT_INFO 09', 'PRODUCT_IMG 09');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (10, 'PRODUCT_NAME 10', 10, 'PRODUCT_INFO 10', 'PRODUCT_IMG 10');

INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (01, 'PRODUCT_NAME 11', 100, 'PRODUCT_INFO 11', 'PRODUCT_IMG 11');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (02, 'PRODUCT_NAME 12', 5000, 'PRODUCT_INFO 12', 'PRODUCT_IMG 12');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (03, 'PRODUCT_NAME 13', 10000, 'PRODUCT_INFO 13', 'PRODUCT_IMG 13');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (04, 'PRODUCT_NAME 14', 3000, 'PRODUCT_INFO 14', 'PRODUCT_IMG 14');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (05, 'PRODUCT_NAME 15', 400, 'PRODUCT_INFO 15', 'PRODUCT_IMG 15');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (06, 'PRODUCT_NAME 16', 700, 'PRODUCT_INFO 16', 'PRODUCT_IMG 16');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (07, 'PRODUCT_NAME 17', 800, 'PRODUCT_INFO 17', 'PRODUCT_IMG 17');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (08, 'PRODUCT_NAME 18', 900, 'PRODUCT_INFO 18', 'PRODUCT_IMG 18');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (09, 'PRODUCT_NAME 19', 1000, 'PRODUCT_INFO 19', 'PRODUCT_IMG 19');
INSERT INTO PRODUCT (S_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_INFO, PRODUCT_IMG) VALUES (10, 'PRODUCT_NAME 20', 2000, 'PRODUCT_INFO 20', 'PRODUCT_IMG 20');

